### ISSUE TITLE
Contrast Sensitivity (CS) for batch size > 1

### ISSUE THREAD

**Issue by maekawataiki** [jorge-pessoa/pytorch-msssim#18]
Thanks for making this implementation.

I found the current implementation may have a small bug if I am not confused.
When throwing batches of the image with size > 1, `cs` returned from `ssim` function have size 1.
This may be expected behaviour when user wants average MS-SSIM score of images in batch (i.e. `size_average=True`), but not ideal when user wants `cs` for each image.
As a result, images within the same batch have a very similar MS-SSIM score even `size_average=False` since they all have the same `mcs`.

Here is some minimal reproduction on Google Colab.
https://colab.research.google.com/drive/1tNWb0QTqn3clnKcMlFeA8QOGJZDDRJe3?usp=sharing

I would appreciate if it is possible to specify whether to average `cs` like `ret` in implementation [here](https://github.com/jorge-pessoa/pytorch-msssim/blob/master/pytorch_msssim/__init__.py#L61-L64)

Proposed change:
Use `size_average` flag to specify the behaviour of `mean` operation on cs.

i.e.

```
    cs = v1 / v2  # contrast sensitivity
    ssim_map = ((2 * mu1_mu2 + C1) * v1) / ((mu1_sq + mu2_sq + C1) * v2)

    if size_average:
        cs = cs.mean()
        ret = ssim_map.mean()
    else:
        cs = cs.mean(1).mean(1).mean(1)
        ret = ssim_map.mean(1).mean(1).mean(1)
```

---
Additional Reference:
Tensorflow Implementation of MS-SSIM. They keep `cs` for each batch. (here, they take mean of width and height and take mean over each channel later)
https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/python/ops/image_ops_impl.py#L3581

**Comment by jorge-pessoa** [comment]
Closed with latest merge. Thank you for your MR
