### ISSUE TITLE
Typo in calculation?

### ISSUE THREAD

**Issue by maekawataiki** [jorge-pessoa/pytorch-msssim#19]
Thanks for making this implementation.

I found the current implementation may have a small typo if I am not confused.

The current implementation of output calculation seems to have the wrong bracket location, changing the result of MS-SSIM score.
https://github.com/jorge-pessoa/pytorch-msssim/blob/master/pytorch_msssim/__init__.py#L104

I think it should be 
`output = torch.prod(pow1[:-1]) * pow2[-1]`
instead of 
`output = torch.prod(pow1[:-1] * pow2[-1])`

---
Reference:

The original Implementation of MS-SSIM in Matlab: https://ece.uwaterloo.ca/~z70wang/research/iwssim/
Their calculation take product over pow1[1:-1] first and multiply pow2[-1]
`overall_msssim = prod(mcs_array(1:level-1).^weight(1:level-1))*(msssim_array(level).^weight(level));`

The original paper of MS-SSIM: https://www.cns.nyu.edu/pub/eero/wang03b.pdf
The calculation is pow2[-1] multiply product over pow1
<img width="338" alt="Screen Shot 2020-10-17 at 8 40 02 AM" src="https://user-images.githubusercontent.com/26317009/96337333-630c9b80-1054-11eb-8540-d7dc34cb3801.png">

**Comment by chledowski** [comment]
Hi, I just found this typo independently. Please make sure this is added to the master, so that others can use the fixed code :)

**Comment by jorge-pessoa** [comment]
Closed with latest merge. Thank you for pointing this out
