### ISSUE TITLE
functools.lru_cache can be used for saving the window

### ISSUE THREAD

**Issue by Yash-5** [jorge-pessoa/pytorch-msssim#8]
There is a todo in the code
`# TODO: store window between calls if possible`

An easy way to do this is to wrap `create_window` with the `functools.lru_cache` wrapper.

https://docs.python.org/3/library/functools.html

**Comment by jorge-pessoa** [comment]
Thank you for your suggestion, I will be integrating this and testing locally to assess the performance difference. Feel free to test it from your side using the branch feature/lru_cache. If a significant difference is present I will merge the changes to master
